### ISSUE TITLE
systemclt does not start the ucarp

### ISSUE THREAD

**Issue by MNibble** [thbe/puppet-ucarp#7]
Feb  2 16:44:10 ip-10-0-2-55 puppet-agent[3643]: Could not start Service[ucarp]: Execution of '/usr/bin/systemctl start ucarp' returned 6: Failed to issue method call: Unit ucarp.service failed to load: No such file or directory.
Feb  2 16:44:10 ip-10-0-2-55 puppet-agent[3643]: (/Stage[main]/Ucarp::Service/Service[ucarp]/ensure) change from stopped to running failed: Could not start Service[ucarp]: Execution of '/usr/bin/systemctl start ucarp' returned 6: Failed to issue method call: Unit ucarp.service failed to load: No such file or directory.

This is related to the https://bugzilla.redhat.com/show_bug.cgi?id=970843
systemctl does start it if you use commands shown in the bug. I know this is more an upstream bug. 

[root@ip-10-0-2-55 ucarp]# cat /etc/centos-release
CentOS Linux release 7.1.1503 (Core)

**Comment by thbe** [comment]
Should be fixed, the virtual ID is now part of the service name which makes this section dynamic.

**Comment by MNibble** [comment]
Thanks !!! - works like a charm now :)

Just in case you want confirmation.
